project:
  type: website
  output-dir: docs

website:
  search: 
    location: sidebar
  page-navigation: true
  page-footer: 
    center: "Marc Thévenin / Ined-Sms / Août 2022-" 
    background: dark

  navbar:
    collapse-below: lg
    left:
      - href: https://mthevenin.github.io/stata_fr/
        text: "Stata Ined"
      - href: https://mthevenin.github.io/stata_graphiques/
        text: "Graphiques"     
      - href: https://mthevenin.github.io/stata_programmation
        text: "Programmation" 
        
    right:
      - icon: github
        href: https://github.com/mthevenin 
      - icon: envelope
        href: mailto:marc.thevenin@ined.fr 
      - href: about.qmd 
        text: "A propos"

  sidebar:
    style: "docked"
    align: left
    collapse-level: 1    
    contents:
      - section: "Formation"
        contents:
          - formation/formation.qmd
          - section: "Chapitre 1: syntaxe"
            contents:
            - formation/formation11.qmd
            - formation/formation12.qmd
            - formation/formation13.qmd
            - formation/formation14.qmd
          - section: "Chapitre 2: macros"
            contents:
            - formation/formation21.qmd
            - formation/formation22.qmd
            - formation/formation23.qmd
          - section: "Chapitre 3: palettes et styles"
            contents:
            - formation/formation31.qmd
            - formation/formation32.qmd
          - section: "Chapitre 4: [A venir]"
          - section: "Chapitre 5: [A venir]"
          - text: "  "  
      - section: "Programmation"
        contents:
          - Stata.qmd
          - programmation/python/python.qmd

format:
  html:
    theme: 
      light:  [yeti, theme-light.scss]          
    code-background: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-title: Sections
    highlight-style: zenburn
    code-tools:
      source: true
number-sections: true
filters:
   - lightbox
lightbox: auto
    