project:
  type: website
  output-dir: docs

website:
  search: 
    location: sidebar
  page-navigation: true
  page-footer: 
    center: "Marc Thévenin - Ined-Sms - Mars 2023" 
    background: dark
  navbar:
    collapse-below: lg
    left:
      - href: https://mthevenin.github.io/stata_fr/
        text: "Stata Ined"  
      - href: https://mthevenin.github.io/stata_graphiques/
        text: "Graphiques"
      - href: https://mthevenin.github.io/stata_programmation/
        text: "Programmation"       

  sidebar:
    pinned: true
    align: center
    tools: 
      - href: about.qmd
      - icon: github
        href: https://github.com/mthevenin
      - icon: envelope
        href: mailto:marc.thevenin@ined.fr 
      - icon: file-person
        href: about.qmd  
        
    style: "docked"
    collapse-level: 1    
    contents:
      - section: "Formation"
        contents:
          - formation/formation.qmd
          - section: "**Syntaxe**"
            contents:
            - formation/formation11.qmd
            - formation/formation12.qmd
            - formation/formation13.qmd
            - formation/formation14.qmd
          - section: "**Macros**"
            contents:
            - formation/formation21.qmd
            - formation/formation22.qmd
            - formation/formation23.qmd
          - section: "**Palettes et styles**"
            contents:
            - formation/formation31.qmd
            - formation/formation32.qmd
          - section: "**Visualisations**"
            contents: 
            - formation/formation41.qmd
            - formation/formation42.qmd            
      - section: "Programmation"
        contents:
          - Stata.qmd
          - programmation/python/python.qmd

format:
  html:
    theme: 
      light:  [yeti, theme-light.scss] 
    css: styles.css
    code-background: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-title: Sections
    highlight-style: zenburn
    code-tools:
      source: true
number-sections: true
filters:
   - lightbox
lightbox: auto
    