---
title: ""
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(Encoding="UTF-8")
```

::: {.callout-important}

## Déplacement des articles dans le support d'accueil

Les courts articles se trouvent maintenant dans le support d'accueil, construit sous forme de blog. Tous les éléments relatifs aux graphiques sont tagués tout naturellement avec le mot **graphique**: [lien](https://mthevenin.github.io/stata_fr/articles/)

:::

::: {.callout-important}
## Prochaines mises à jour

Introduction des nouveautés de Stata 18

- Modification de la syntaxe avec l'option `colorvar` [<https://www.stata.com/new-in-stata/graph-colors-by-variable/>]. Cela va modifier beaucoup de chaose
- Nouveau thème par défaut. Enfin!!!! 
- Vu le caractère récent de ces implémentations, le support ne sera pas modifié sous l'hypothèse que toutes les personnes bénéficient de ces ajouts.


- Je suis toujours à la traine  pour la partie visualisation (chapitre 4 )

:::

**Les programmes des chapitres sont disponibles aux adresses suivantes**: 

* **Chapitre 1**: [Programme Partie 1](formation/programme_p1.do)
* **Chapitre 2**: [Programme Partie 2](formation/programme_p2.do)
* **Chapitre 4**: Programme Partie 4
  *  [Introduction](formation/programme_p4a.do)
  * [Distributions](formation/programme_p4b.do)

<br>

**INTRODUCTION A LA SEMIOLOGIE GRAPHIQUE (Bénédicte Garnier - Ined-SMS)**

Lien vers le document: [Lien](BGIntro_ppt.pdf)

<iframe src="BGIntro_ppt.pdf" height="500" width="900" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay"></iframe>



-    Support réalisé avec [Posit-Rstudio](https://posit.co/) - [Quarto](https://quarto.org).
-    Version Stata: [17-SE](https://www.stata.com/)

